spring:
  application:
    name: shopping
  profiles:
    active: local
  thymeleaf:
    cache: false
    mode: HTML
    suffix: .html
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
    add-mappings: true
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shopping-noto?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root