spring:
  application:
    name: shopping
  profiles:
    active: local
  thymeleaf:
    cache: false
    mode: HTML
    suffix: .html
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
    add-mappings: true
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.203.7.77:3306/searchdb?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: wisenut
    password: wisenut123